name: release
on: workflow_dispatch

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set Current VSCode Version
      #   run: |
      #     CURRENT_VERSION=$(node -p 'require("./packages/typescript-explorer-vscode/package.json").version')
      #     echo "CURRENT_VSCODE_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Set Current Version
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build

      - name: Package Vsix
        run: |
          VSIX_FILENAME=typescript-explorer-v${{ env.CURRENT_VERSION }}.vsix
          echo "VSIX_FILENAME=${VSIX_FILENAME}" >> $GITHUB_ENV
          yarn workspace typescript-explorer package -o ./${VSIX_FILENAME}

      - name: Get Changelog
        run: |
          echo "CHANGELOG_MD<<__EOF__" >> $GITHUB_ENV
          yarn --silent changelog:get >> $GITHUB_ENV
          echo "__EOF__" >> $GITHUB_ENV

      - name: Tag Check
        id: tag_check
        run: |
          GET_API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/git/ref/tags/v${CURRENT_VERSION}"
          http_status_code=$(curl -LI $GET_API_URL -o /dev/null -w '%{http_code}\n' -s \
            -H "Authorization: token ${GITHUB_TOKEN}")
          if [ "$http_status_code" -ne "404" ] ; then
            echo "::set-output name=exists_tag::true"
          else
            echo "::set-output name=exists_tag::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        if: steps.tag_check.outputs.exists_tag == 'false'
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ env.CURRENT_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Create Release
        id: create_release
        if: steps.tag_check.outputs.exists_tag == 'false'
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ env.CURRENT_VERSION }}
          body: |
            ${{ env.CHANGELOG_MD }}
          artifacts: ./packages/typescript-explorer-vscode/${{ env.VSIX_FILENAME }}
          draft: false
